version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"

    ## setup the environment ,, install node js with  version 16.13.2 ,, setup aws cli and elastic beanstalk
    steps:
      - node/install:
          node-version: "16.13.2"
      - checkout
      - aws-cli/setup
      - eb/setup

      ## install dependencies for frontend
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install --force

        ## install dependencies for backend
      - run:
          name: Back-End Install
          command: |
            npm run backend:install

      ## build the frontend project
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build

      ## build the backend project
      - run:
          name: Back-End Build
          command: |
            npm run backend:build

      ## deploy frontend
      - run:
          name: Front-End deploy
          command: |
            npm run frontend:deploy

      ## deploy backend
      - run:
          name: Back-End deploy
          command: |
            npm run backend:deploy
